name: Manual workflow
on: workflow_dispatch
jobs:
  setEnviroment:
    runs-on: ubuntu-latest
    steps:
      - name: init enviroment
        run: echo "iniciandin"
      - name: finish enviroment 
        run: echo "finalizanding"
        
